/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leapfrog.cps.StudentADDUI;

import com.leapfrog.cpg.controller.Controller;
import com.leapfrog.cps.DAO.StudentDAO;
import com.leapfrog.cps.DAOImpl.StudentDAOImpl;
import com.leapfrog.cps.util.Student;
import java.util.List;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author AM3ET
 */
public class StudentDetailsUI extends javax.swing.JFrame {
    StudentDAO stdDAO = new StudentDAOImpl();
    Controller ctrl = new Controller(stdDAO);
    /**
     * Creates new form StudentDetailsUI
     */
    public StudentDetailsUI() {
        initComponents();
        ctrl.show();
        String[] columns = {"ID","First Name","Last Name","Email","Contact","Status"};
        tbl_student.setModel(new StudentTableModule(columns,stdDAO.getAll()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_student = new javax.swing.JTable();
        lbladd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        tbl_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Email", "Contact"
            }
        ));
        jScrollPane1.setViewportView(tbl_student);

        lbladd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leapfrog/cps/resources/add.png"))); // NOI18N
        lbladd.setText("Add");
        lbladd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonClick(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leapfrog/cps/resources/refresh.png"))); // NOI18N
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbladd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbladd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonClick
        new StudentADDUI().setVisible(true);    
    }//GEN-LAST:event_addButtonClick

    /**
     * @param args the command line arguments
     */
    

    private class StudentTableModule extends AbstractTableModel {

        private String[] columns;
        private List<Student> studentList;

        public StudentTableModule(String[] columns, List<Student> studentList) {
            this.columns = columns;
            this.studentList = studentList;
        }

        @Override
        public int getRowCount() {
            return studentList.size();
        }

        @Override
        public int getColumnCount() {
            return columns.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Student std = studentList.get(rowIndex);
            switch(columnIndex){
                case 0:
                    return std.getId();
                case 1:
                    return std.getfName();
                case 2:
                    return std.getlName();
                case 3:
                    return std.getEmail();
                case 4:
                    return std.getContact();
                case 5:
                    return std.isStatus();
            }
            return null;
        }
        public String getColumnName(int columnIndex){ 
            return columns[columnIndex];  }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lbladd;
    private javax.swing.JTable tbl_student;
    // End of variables declaration//GEN-END:variables
}
